FROM apache/airflow:2.9.0-python3.10

USER root

# Install OpenJDK-17
RUN apt update && \
    apt-get install -y default-jre && \
    apt-get install -y ant && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

USER airflow

COPY requirements.txt .
RUN pip install -r requirements.txt